### ISSUE TITLE
Crashes because of IncompatibleClassChangeError with UiUtils

### ISSUE THREAD

**Issue by Brawaru** [sk22/mastodos#60]
In the bottom bar you can hold your profile picture for it to open menu where you can add other accounts and switch between them. It works in official app, however it crashes the app in mastodos.

<details>
<summary>Logcat slice with crash</summary>

```
11-20 04:22:19.309 14153 14153 D AndroidRuntime: Shutting down VM
11-20 04:22:19.313 14153 14153 E AndroidRuntime: FATAL EXCEPTION: main
11-20 04:22:19.313 14153 14153 E AndroidRuntime: Process: org.joinmastodon.android.sk, PID: 14153
11-20 04:22:19.313 14153 14153 E AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'e1.r' appears in /data/app/org.joinmastodon.android.sk-1/base.apk)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at e1.r.p(:4)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at z0.d$b.l0(:8)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at z0.d$b.b0(:1)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at a0.b.Y(:2)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at z0.d$c.G(:1)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at z0.d$c.v(:1)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at a0.d.v(:1)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.w(:1)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.c(:7)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$v.H(:7)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$v.I(:47)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$v.p(:1)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$v.o(:1)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.m$c.d(:3)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.m.l2(:1)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.m.R1(:9)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.m.V0(:65)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.I(:12)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onMeasure(:13)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:606)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5466)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-20 04:22:19.313 14153 14153 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-20 04:22:19.316  1787  1829 W ActivityManager:   Force finishing activity org.joinmastodon.android.sk/org.joinmastodon.android.MainActivity
```
</details>

**Comment by sk22** [comment]
huhh, that's odd, it works for me…

**Comment by sk22** [comment]
so, i just published a new version, where i disabled minification/obfuscation, so i can debug stuff more easily. could you maybe send me a new logcat with the new version?

**Comment by Brawaru** [comment]
Here you go :)

<details>
<summary>Logcat slices</summary>

- When trying to open account switcher
```
11-21 00:01:58.025  7490  7490 D AndroidRuntime: Shutting down VM
11-21 00:01:58.034  7490  7490 E AndroidRuntime: FATAL EXCEPTION: main
11-21 00:01:58.034  7490  7490 E AndroidRuntime: Process: org.joinmastodon.android.sk, PID: 7490
11-21 00:01:58.034  7490  7490 E AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'org.joinmastodon.android.ui.utils.UiUtils' appears in /data/app/org.joinmastodon.android.sk-2/base.apk:classes15.dex)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at org.joinmastodon.android.ui.utils.UiUtils.enablePopupMenuIcons(UiUtils.java:623)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at org.joinmastodon.android.ui.AccountSwitcherSheet$AccountViewHolder.onBind(AccountSwitcherSheet.java:217)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at org.joinmastodon.android.ui.AccountSwitcherSheet$AccountViewHolder.onBind(AccountSwitcherSheet.java:179)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at me.grishka.appkit.utils.BindableViewHolder.bind(BindableViewHolder.java:33)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at org.joinmastodon.android.ui.AccountSwitcherSheet$AccountsAdapter.onBindViewHolder(AccountSwitcherSheet.java:164)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at org.joinmastodon.android.ui.AccountSwitcherSheet$AccountsAdapter.onBindViewHolder(AccountSwitcherSheet.java:146)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at me.grishka.appkit.utils.MergeRecyclerAdapter.onBindViewHolder(MergeRecyclerAdapter.java:123)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7256)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7339)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6197)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6463)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6303)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6299)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2328)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1629)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1589)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:666)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4300)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3677)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:606)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
11-21 00:01:58.034  7490  7490 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-21 00:01:58.039  2024  2061 W ActivityManager:   Force finishing activity org.joinmastodon.android.sk/org.joinmastodon.android.MainActivity
11-21 00:01:58.122  2024  4130 I OpenGLRenderer: Initialized EGL, version 1.4
11-21 00:01:58.568  2024  2070 W ActivityManager: Activity pause timeout for ActivityRecord{3df28f2 u0 org.joinmastodon.android.sk/org.joinmastodon.android.MainActivity t1075 f}
```

- When scrolling through settings
```
11-21 00:02:40.879 10249 10249 D AndroidRuntime: Shutting down VM
11-21 00:02:40.880 10249 10249 E AndroidRuntime: FATAL EXCEPTION: main
11-21 00:02:40.880 10249 10249 E AndroidRuntime: Process: org.joinmastodon.android.sk, PID: 10249
11-21 00:02:40.880 10249 10249 E AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'org.joinmastodon.android.ui.utils.UiUtils' appears in /data/app/org.joinmastodon.android.sk-2/base.apk:classes15.dex)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at org.joinmastodon.android.ui.utils.UiUtils.enablePopupMenuIcons(UiUtils.java:623)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at org.joinmastodon.android.fragments.SettingsFragment$NotificationPolicyViewHolder.<init>(SettingsFragment.java:667)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at org.joinmastodon.android.fragments.SettingsFragment$SettingsAdapter.onCreateViewHolder(SettingsFragment.java:507)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at org.joinmastodon.android.fragments.SettingsFragment$SettingsAdapter.onCreateViewHolder(SettingsFragment.java:498)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7297)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6419)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:287)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:344)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:360)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:367)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:398)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5466)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-21 00:02:40.880 10249 10249 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-21 00:02:40.882  2024  5141 W ActivityManager:   Force finishing activity org.joinmastodon.android.sk/org.joinmastodon.android.MainActivity
11-21 00:02:40.990  2024  4130 I OpenGLRenderer: Initialized EGL, version 1.4
11-21 00:02:41.054  2024  2034 I art     : Background partial concurrent mark sweep GC freed 46796(2MB) AllocSpace objects, 4(96KB) LOS objects, 33% free, 24MB/36MB, paused 2.308ms total 157.729ms
11-21 00:02:41.433  2024  2070 W ActivityManager: Activity pause timeout for ActivityRecord{64365bd u0 org.joinmastodon.android.sk/org.joinmastodon.android.MainActivity t1076 f}
```

- When trying to change post visibility
```
11-21 00:03:15.259 12492 12492 D AndroidRuntime: Shutting down VM
11-21 00:03:15.260 12492 12492 E AndroidRuntime: FATAL EXCEPTION: main
11-21 00:03:15.260 12492 12492 E AndroidRuntime: Process: org.joinmastodon.android.sk, PID: 12492
11-21 00:03:15.260 12492 12492 E AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'org.joinmastodon.android.ui.utils.UiUtils' appears in /data/app/org.joinmastodon.android.sk-2/base.apk:classes15.dex)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at org.joinmastodon.android.ui.utils.UiUtils.enablePopupMenuIcons(UiUtils.java:623)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at org.joinmastodon.android.fragments.ComposeFragment.onVisibilityClick(ComposeFragment.java:1317)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at org.joinmastodon.android.fragments.ComposeFragment.$r8$lambda$lQYRU3e3C90M-hU74NJtdcAe-Pk(ComposeFragment.java)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at org.joinmastodon.android.fragments.ComposeFragment$$ExternalSyntheticLambda2.onClick(D8$$SyntheticClass)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at android.view.View.performClick(View.java:5204)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:21156)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5466)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-21 00:03:15.260 12492 12492 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-21 00:03:15.261  2024  4976 W ActivityManager:   Force finishing activity org.joinmastodon.android.sk/org.joinmastodon.android.MainActivity
11-21 00:03:15.335  2024  4130 I OpenGLRenderer: Initialized EGL, version 1.4
11-21 00:03:15.785  2024  2070 W ActivityManager: Activity pause timeout for ActivityRecord{ae22f3c u0 org.joinmastodon.android.sk/org.joinmastodon.android.MainActivity t1077 f}
```

</details>

It seems like this code wasn't touched from upstream, but with official Mastodon app it works and here it doesn't, weird.

**Comment by sk22** [comment]
probably because the latest released upstream version is from july, and well, quite some things have changed since then :')

**Comment by sk22** [comment]
can i maybe build the upstream app for you so you can try it out and we can open a bug report on the upstream repo?

**Comment by Brawaru** [comment]
Sure thing! I have no idea how to build android stuff myself and the last time I tried something like that I failed miserably :D

**Comment by sk22** [comment]
okay - there! https://gist.github.com/sk22/28d4b4b0b05fe3219121b848373aa90e/raw/b9e8cb48e9958086af2515dd2650e9fbfc0351b4/mastodon-githubRelease.apk

**Comment by Brawaru** [comment]
Confirmed upstream issue, created https://github.com/mastodon/mastodon-android/issues/399. Thanks for that test build!
