### ISSUE TITLE
Random crashes in App

### ISSUE THREAD

**Issue by karano-techie** [sk22/mastodos#76]
I am getting random crashes in the app like even while scrolling through the feed ,expanding posts etc.

I don't know whats exaxtly causing it but they have been very frequent and making the app unusable for me.
Some might be related to previous known issues but do have a look at it.

![logcat_11-21-2022_20-45-38.txt](https://github.com/sk22/mastodos/files/10057725/logcat_11-21-2022_20-45-38.txt)

**Comment by sk22** [comment]
Okay, so, since this doesn't happen for me, here's my plan:
Starting with the next release, I will also attach an unmodified, upstream build of Mastodon for Android. (Built from source – not the latest Play Store release from July). Once I did that, please try and see if the issue persists with the unmodified version.

**Comment by sk22** [comment]
Actually, I did find an interesting error in your log that's probably my fault:

```
java.lang.IllegalStateException: Fragment ProfileFragment{e3c87b8} not attached to Activity
	at android.app.Fragment.getResources(Fragment.java:780)
	at android.app.Fragment.getString(Fragment.java:815)
	at org.joinmastodon.android.fragments.ProfileFragment.updateRelationship(ProfileFragment.java:651)
	at org.joinmastodon.android.fragments.ProfileFragment.-$$Nest$mupdateRelationship(Unknown Source:0)
	at org.joinmastodon.android.fragments.ProfileFragment$8.onSuccess(ProfileFragment.java:629)
	at org.joinmastodon.android.fragments.ProfileFragment$8.onSuccess(ProfileFragment.java:624)
	at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8089)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

The other errors I see are either caused by the old new image loader (from upstream, will be updated in next release) or because of #71.
